version: '3.8'

services:
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
      - redis-node-1-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.10

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
      - redis-node-2-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.11

  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
    networks:
      - redis-cluster
    command: >
      sh -c "
        sleep 10 &&
        redis-cli --cluster create 
        172.20.0.10:7000 
        172.20.0.11:7001 
        --cluster-replicas 1 
        --cluster-yes
      "

volumes:
  redis-node-1-data:
  redis-node-2-data:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16